name: Run Gosec and ZAP Scan
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v3

      - name: Generate SBOM
        id: sbom
        uses: anchore/sbom-action@v0 

      - name: Run Gosec Security Scanner
        id: gosec
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
