name: GoSecTest

on:
  push:
    branches:
      - main

jobs:
  GoSecScan:
    name: GoSec Scan
    runs-on: ubuntu-latest

    steps:
      - name: Gosec Security Checker
        uses: securego/gosec@v2.18.2
        with:
          # Arguments for gosec
          args: ""
